version: '3.8'
services:
db:
  image: postgres
  restart: always
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 12345
    POSTGRES_DB: onboarding
    container_name: postgres-db-onboarding
